runtime: python37
# Configs static across environments
env_variables:
    PUBSUB_TOPIC: tilt-gateways
    BQ_DATASET: tilt_log_dataset
    BQ_TABLE: tilt_log_table
    BQ_KEYPATH: "keys/sa-bq-loader-key.json"
includes:
- env_config.yaml

#env_config should include following environment variables:
# PUBSUB_TOPIC, PUBSUB_VERIFICATION_TOKEN, GATEWAYCONFIG
